### ISSUE TITLE
Compile-time function execution on functions not marked constexpr

### ISSUE THREAD

**Issue by uBakaChan** [Sumandora/XorString#1]
![image](https://github.com/user-attachments/assets/08f31cf5-6803-459b-ae02-4012fd637b2d)

**Comment by Sumandora** [comment]
I should probably close this outright, due to your obvious toxicity, but I'll let it slide once.

The library consists of two functions. One marked consteval, the other not marked with constexpr or consteval. This means that a C++23 compliant compiler is required to execute the encryption at compile-time and the decryption at runtime. Some compilers may opt to execute the decryption at compile time as well, however since C++ does not offer a way to force execution to be run at runtime other than removing constexpr and consteval, there is nothing to be done here. Please consult your compiler manual to see if it offers a way to turn off compile time function execution for functions that aren't marked with constexpr.

**Comment by uBakaChan** [comment]
> I should probably close this outright, due to your obvious toxicity, but I'll let it slide once.
> 
> The library consists of two functions. One marked consteval, the other not marked with constexpr or consteval. This means that a C++23 compliant compiler is required to execute the encryption at compile-time and the decryption at runtime. Some compilers may opt to execute the decryption at compile time as well, however since C++ does not offer a way to force execution to be run at runtime other than removing constexpr and consteval, there is nothing to be done here. Please consult your compiler manual to see if it offers a way to turn off compile time function execution for functions that aren't marked with constexpr.

my bad if that come as toxic.  dint mean to.. 🙏.. I just cant think of any title that relates to an issue because i dont know the issue to begin with.. im sorry. i do better next time.

**Comment by Sumandora** [comment]
> > I should probably close this outright, due to your obvious toxicity, but I'll let it slide once.
> > The library consists of two functions. One marked consteval, the other not marked with constexpr or consteval. This means that a C++23 compliant compiler is required to execute the encryption at compile-time and the decryption at runtime. Some compilers may opt to execute the decryption at compile time as well, however since C++ does not offer a way to force execution to be run at runtime other than removing constexpr and consteval, there is nothing to be done here. Please consult your compiler manual to see if it offers a way to turn off compile time function execution for functions that aren't marked with constexpr.
> 
> my bad if that come as toxic. dint mean to.. 🙏.. I just cant think of any title that relates to an issue because i dont know the issue to begin with.. im sorry. i do better next time.

First of all, the compiler name, version, parameters and other compilation-related data would be helpful.
